grid_search:
  class: GridSearchCV
  module: catboost
  params:
    cv: 3
    verbose: 3
model_selection:
  module_0:
  class: CatBoostClassifier
  module: catboost
  params:
    iterations: 500
    learning_rate: 6
  search_param_grid:
    learning_rate:
     - 4
     - 6
    iterations:
     - 300
     - 250